#ifndef IRC_MESSAGE_H
#define IRC_MESSAGE_H

#include <string>
#include "ParamCollection.h"

class Session;

class IrcMessage
{
public:
	enum
	{
		MAX_LENGTH = 512
	};

	enum eErr
	{
		ERR_NONE = 0,
		ERR_MESSAGE_TOO_LONG
	};

	enum eCommand
	{
		COMMAND_UNKNOWN,		
		COMMAND_PASS,
		COMMAND_NICK,
		COMMAND_USER,
		COMMAND_OPER, //yoseo: need command
		COMMAND_KILL, //yoseo: need command
		COMMAND_QUIT,
		COMMAND_JOIN,
		COMMAND_PART,
		COMMAND_MODE,
		COMMAND_TOPIC,
		COMMAND_NAMES,
		COMMAND_LIST,
		COMMAND_INVITE,
		COMMAND_KICK,
		COMMAND_PRIVMSG,
		COMMAND_PING,
		COMMAND_PONG,
		COMMAND_ERROR,
		COMMAND_COUNT,
		NUMERIC_ERR_NEEDMOREPARAMS,
		NUMERIC_ERR_NONICKNAMEGIVEN,
		NUMERIC_ERR_ERRONEUSNICKNAME,
		NUMERIC_ERR_NICKNAMEINUSE,
		NUMERIC_ERR_NICKCOLLISION,
		//err_reply
		NUMERIC_RPL_WELCOME, //"Welcome to the Internet Relay Network <nick>!<user>@<host>"
    NUMERIC_RPL_YOURHOST, //"Your host is <servername>, running version <ver>"
    NUMERIC_RPL_CREATED, //"This server was created <date>"
    NUMERIC_RPL_MYINFO, //"<servername> <version> <available user modes> <available channel modes>"
		NUMERIC_ERR_NOSUCHNICK,
		NUMERIC_ERR_NOSUCHSERVER,
		NUMERIC_ERR_NOSUCHCHANNEL,
		NUMERIC_ERR_CANNOTSENDTOCHAN,
		NUMERIC_ERR_TOOMANYCHANNELS,
		NUMERIC_ERR_WASNOSUCHNICK,
		NUMERIC_ERR_TOOMANYTARGETS,
		NUMERIC_408,
		NUMERIC_ERR_NOORIGIN,
		NUMERIC_410,
		NUMERIC_ERR_NORECIPIENT,
		NUMERIC_ERR_NOTEXTTOSEND,
		NUMERIC_ERR_NOTOPLEVEL,
		NUMERIC_ERR_WILDTOPLEVEL,
		NUMERIC_415,
		NUMERIC_416,
		NUMERIC_417,
		NUMERIC_418,
		NUMERIC_419,
		NUMERIC_420,
		NUMERIC_ERR_UNKNOWNCOMMAND,
		NUMERIC_ERR_NOMOTD,
		NUMERIC_ERR_NOADMININFO,
		//NUMERIC_ERR_NOADMININFO = 423 already given above
		NUMERIC_ERR_FILEERROR,
		NUMERIC_425,
		NUMERIC_426,
		NUMERIC_427,
		NUMERIC_428,
		NUMERIC_429,
		NUMERIC_430,
		//NUMERIC_ERR_NONICKNAMEGIVEN = 431 already given above
		//NUMERIC_ERR_ERRONEUSNICKNAME = 432 already given above
		//NUMERIC_ERR_NICKNAMEINUSE = 433 already given above
		NUMERIC_434,
		NUMERIC_435,
		//NUMERIC_ERR_NICKCOLLISION = 436 already given above
		NUMERIC_437,
		NUMERIC_438,
		NUMERIC_439,
		NUMERIC_440,
		NUMERIC_ERR_USERNOTINCHANNEL,
		NUMERIC_ERR_NOTONCHANNEL,
		NUMERIC_ERR_USERONCHANNEL,
		NUMERIC_ERR_NOLOGIN,
		NUMERIC_ERR_SUMMONDISABLED,
		NUMERIC_ERR_USERSDISABLED,
		NUMERIC_447,
		NUMERIC_448,
		NUMERIC_449,
		NUMERIC_450,
		NUMERIC_ERR_NOTREGISTERED,
		NUMERIC_452,
		NUMERIC_453,
		NUMERIC_454,
		NUMERIC_455,
		NUMERIC_456,
		NUMERIC_457,
		NUMERIC_458,
		NUMERIC_459,
		NUMERIC_460,
		//NUMERIC_ERR_NEEDMOREPARAMS = 461 already given above
		NUMERIC_ERR_ALREADYREGISTRED,
		NUMERIC_ERR_NOPERMFORHOST,
		NUMERIC_ERR_PASSWDMISMATCH,
		NUMERIC_ERR_YOUREBANNEDCREEP,
		NUMERIC_ERR_YOUWILLBEBANNED, //reserved numeric
		NUMERIC_ERR_KEYSET,
		NUMERIC_468,
		NUMERIC_469,
		NUMERIC_470,
		NUMERIC_ERR_CHANNELISFULL,
		NUMERIC_ERR_UNKNOWNMODE,
		NUMERIC_ERR_INVITEONLYCHAN,
		NUMERIC_ERR_BANNEDFROMCHAN,
		NUMERIC_ERR_BADCHANNELKEY,
		NUMERIC_ERR_BADCHANMASK, //reserved numeric
		NUMERIC_477,
		NUMERIC_478,
		__NUMERIC_ERR_ILEGGLECHANNELNAME,
		NUMERIC_480,
		NUMERIC_ERR_NOPRIVILEGES,
		NUMERIC_ERR_CHANOPRIVSNEEDED,
		NUMERIC_ERR_CANTKILLSERVER,
		NUMERIC_484,
		NUMERIC_485,
		NUMERIC_486,
		NUMERIC_487,
		NUMERIC_488,
		NUMERIC_489,
		NUMERIC_490,
		NUMERIC_ERR_NOOPERHOST,
		NUMERIC_ERR_NOSERVICEHOST, //reserved numeric
		NUMERIC_493,
		NUMERIC_494,
		NUMERIC_495,
		NUMERIC_496,
		NUMERIC_497,
		NUMERIC_498,
		NUMERIC_499,
		NUMERIC_500,
		NUMERIC_ERR_UMODEUNKNOWNFLAG,
		NUMERIC_ERR_USERSDONTMATCH,
		//command responses
		NUMERIC_RPL_NONE,
		NUMERIC_RPL_AWAY,
		NUMERIC_RPL_USERHOST,
		NUMERIC_RPL_ISON,
		NUMERIC_304,
		NUMERIC_RPL_UNAWAY,
		NUMERIC_RPL_NOWAWAY,
		NUMERIC_307,
		NUMERIC_308,
		NUMERIC_309,
		NUMERIC_310,
		NUMERIC_RPL_WHOISUSER,
		NUMERIC_RPL_WHOISSERVER,
		NUMERIC_RPL_WHOISOPERATOR,
		NUMERIC_RPL_WHOWASUSER,
		NUMERIC_RPL_ENDOFWHO,
		NUMERIC_RPL_WHOISCHANOP, //reserved numeric
		NUMERIC_RPL_WHOISIDLE,
		NUMERIC_RPL_ENDOFWHOIS,
		NUMERIC_RPL_WHOISCHANNELS, //319
		NUMERIC_320,
		NUMERIC_RPL_LISTSTART,
		NUMERIC_RPL_LIST,
		NUMERIC_RPL_LISTEND,
		NUMERIC_RPL_CHANNELMODEIS,
		NUMERIC_325,
		NUMERIC_326,
		NUMERIC_327,
		NUMERIC_328,
		NUMERIC_329,
		NUMERIC_330,
		NUMERIC_RPL_NOTOPIC,
		NUMERIC_RPL_TOPIC,
		NUMERIC_333,
		NUMERIC_334,
		NUMERIC_335,
		NUMERIC_336,
		NUMERIC_337,
		NUMERIC_338,
		NUMERIC_339,
		NUMERIC_340,
		NUMERIC_RPL_INVITING,
		NUMERIC_RPL_SUMMONING,
		NUMERIC_343,
		NUMERIC_344,
		NUMERIC_345,
		NUMERIC_346,
		NUMERIC_347,
		NUMERIC_348,
		NUMERIC_349,
		NUMERIC_350,
		NUMERIC_RPL_VERSION,
		NUMERIC_RPL_WHOREPLY,
		NUMERIC_RPL_NAMREPLY,
		NUMERIC_354,
		NUMERIC_355,
		NUMERIC_356,
		NUMERIC_357,
		NUMERIC_358,
		NUMERIC_359,
		NUMERIC_360,
		NUMERIC_RPL_KILLDONE, //reserved numeric
		NUMERIC_RPL_CLOSING, //reserved numeric
		NUMERIC_RPL_CLOSEEND, //reserved numeric
		NUMERIC_RPL_LINKS,
		NUMERIC_RPL_ENDOFLINKS,
		NUMERIC_RPL_ENDOFNAMES,
		NUMERIC_RPL_BANLIST,
		NUMERIC_RPL_ENDOFBANLIST,
		NUMERIC_RPL_ENDOFWHOWAS,
		NUMERIC_370,
		NUMERIC_RPL_INFO,
		NUMERIC_RPL_MOTD,
		NUMERIC_RPL_INFOSTART, //reserved numeric
		NUMERIC_RPL_ENDOFINFO,
		NUMERIC_RPL_MOTDSTART,
		NUMERIC_RPL_ENDOFMOTD,
		NUMERIC_377,
		NUMERIC_378,
		NUMERIC_379,
		NUMERIC_380,
		NUMERIC_RPL_YOUREOPER,
		NUMERIC_RPL_REHASHING,
		NUMERIC_383,
		NUMERIC_RPL_MYPORTIS, //reserved numeric
		NUMERIC_385,
		NUMERIC_386,
		NUMERIC_387,
		NUMERIC_388,
		NUMERIC_389,
		NUMERIC_390,
		NUMERIC_RPL_TIME,
		NUMERIC_RPL_USERSSTART,
		NUMERIC_RPL_USERS,
		NUMERIC_RPL_ENDOFUSERS,
		NUMERIC_RPL_NOUSERS,
		
		NUMERIC_RPL_TRACELINK,
		NUMERIC_RPL_TRACECONNECTING,
		NUMERIC_RPL_TRACEHANDSHAKE,
		NUMERIC_RPL_TRACEUNKNOWN,
		NUMERIC_RPL_TRACEOPERATOR,
		NUMERIC_RPL_TRACEUSER,
		NUMERIC_RPL_TRACESERVER,
		NUMERIC_207,
		NUMERIC_RPL_TRACENEWTYPE,
		NUMERIC_RPL_TRACECLASS, //reserved numeric
		NUMERIC_210,
		NUMERIC_RPL_STATSLINKINFO,
		NUMERIC_RPL_STATSCOMMANDS,
		NUMERIC_RPL_STATSCLINE,
		NUMERIC_RPL_STATSNLINE,
		NUMERIC_RPL_STATSILINE,
		NUMERIC_RPL_STATSKLINE,
		NUMERIC_RPL_STATSQLINE, //reserved numeric
		NUMERIC_RPL_STATSYLINE,
		NUMERIC_RPL_ENDOFSTATS,
		NUMERIC_220,
		NUMERIC_RPL_UMODEIS,
		NUMERIC_222,
		NUMERIC_223,
		NUMERIC_224,
		NUMERIC_225,
		NUMERIC_226,
		NUMERIC_227,
		NUMERIC_228,
		NUMERIC_229,
		NUMERIC_230,
		NUMERIC_RPL_SERVICEINFO, //reserved numeric
		NUMERIC_RPL_ENDOFSERVICES, //reserved numeric
		NUMERIC_RPL_SERVICE, //reserved numeric
		NUMERIC_RPL_SERVLIST, //reserved numeric
		NUMERIC_RPL_SERVLISTEND, //reserved numeric
		NUMERIC_236,
		NUMERIC_237,
		NUMERIC_238,
		NUMERIC_239,
		NUMERIC_240,
		NUMERIC_RPL_STATSLLINE,
		NUMERIC_RPL_STATSUPTIME,
		NUMERIC_RPL_STATSOLINE,
		NUMERIC_RPL_STATSHLINE,
		NUMERIC_245,
		NUMERIC_246,
		NUMERIC_247,
		NUMERIC_248,
		NUMERIC_249,
		NUMERIC_250,
		NUMERIC_RPL_LUSERCLIENT,
		NUMERIC_RPL_LUSEROP,
		NUMERIC_RPL_LUSERUNKNOWN,
		NUMERIC_RPL_LUSERCHANNELS,
		NUMERIC_RPL_LUSERME,
		NUMERIC_RPL_ADMINME,
		NUMERIC_RPL_ADMINLOC1,
		NUMERIC_RPL_ADMINLOC2,
		NUMERIC_RPL_ADMINEMAIL,
		NUMERIC_260,
		NUMERIC_RPL_TRACELOG,
		NUMERIC_262,
		NUMERIC_263,

		NUMERIC_COUNT
	};

friend
	eErr ForwardIrcMessage(const IrcMessage& message, Session* pSession);
public:
	IrcMessage();
	IrcMessage(const IrcMessage& other);
	IrcMessage(const std::string& rawMessage);
	virtual ~IrcMessage();

	IrcMessage& operator=(const IrcMessage& other);

	eCommand GetCommand() const;
	const std::string& GetPrefix() const;
	const ParamCollection& GetParams() const;

	void SetCommand(eCommand command);
	void SetPrefix(const std::string& prefix);
	void AddParam(const std::string& param);

private:
	eCommand toCommand(const std::string& commandString);

private:
	eCommand mCommand;
	std::string mPrefix;
	ParamCollection mParams;

	static const char* smCommandStrings[NUMERIC_COUNT];
};

IrcMessage::eErr ForwardIrcMessage(const IrcMessage& message, Session* pSession);

#endif
